version: '3'
services:
  web:
    image: nginx:1.17.1
    volumes:
      - ./docker/nginx/mysite.jp.template:/etc/nginx/conf.d/conf.template
    ports:
      - "8000:80"
    environment:
      - NGINX_PHP_PATH=php:9000
      - NGINX_SERVER_NAME=local.mysite.jp
      - NGINX_ROOT=/var/www/test/public
    command: > 
      /bin/bash -c "envsubst '
      $$NGINX_PHP_PATH
      $$NGINX_SERVER_NAME
      $$NGINX_ROOT
      '< /etc/nginx/conf.d/conf.template > 
      /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - php
  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/test
    depends_on:
      - db
  db:
    build: ./docker/db
    ports:
      - 3366:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test_db
      MYSQL_PASSWORD: test_db!
      MYSQL_DATABASE: test_db
    volumes:
      - db-data:/var/lib/mysql
  s3:
    image: minio/minio
    ports:
      - "9001:9000"
    volumes:
      - ./docker/minio/data:/data
    command: server /data
    environment:
      MINIO_ACCESS_KEY: local_test_s3_access_key
      MINIO_SECRET_KEY: local_test_s3_secret_key
volumes:
  db-data:
    driver: local

